### ISSUE TITLE
Scalebar does not scale

### ISSUE THREAD

**Issue by gnies** [guiwitz/microfilm#14]
Hallo, 
This is essentially the first time I post an issue on github, so I already apologize in case this is not the right format.
I am experiencing some trouble with the scale bar. Essentially, for me, a convenient way of zooming into the image, especially when I already plotted other markers, is the following: 

```
import skimage.io
from microfilm.microplot import microshow
import matplotlib.pyplot as plt


image = skimage.io.imread('coli_nucl_ori_ter.tif')
time = 10

fig, ax = plt.subplots()
# zooming into the first 10 pixel of the image
plt.xlim((0, 10))
plt.ylim((0, 10))
microim = microshow(images=image[:, time, :, :], fig_scaling=5,
                 cmaps=['pure_blue','pure_red', 'pure_green'],
                 unit='um', scalebar_size_in_units=3, scalebar_unit_per_pix=0.065, scalebar_text_centered=True, scalebar_font_size=0.04,label_text='A', label_font_size=0.04, ax=ax)

plt.show()
```
What then happens it that the scale bar seems to scale correctly with the image, but then indicates incorrect distances. Naturally, I would prefer it to give a warning, the correct number or just disappear, but not to provide an incorrect number. Could this be technically possible? So far, I solved the issue, resorting to the matplotlib-scalebar package. Thanks in advance for any suggestions and also thanks for the great package in general :)

**Comment by guiwitz** [comment]
Hi @gnies,

thanks for the very clear issue description (in particular the minimal reproducible example is very helpful!).

The way you are "zooming in" using ```plt.xlim``` and ```plt.ylim``` is not a case I had in mind. I would rather expect people to use a crop of the image e.g. ```image[:, time, 0:10, 0:10]```. As you still pass the full image to the ```microshow``` function, the computation of the scalebar fails. 

Anyway, I had planned for a long time to use matplotlib-scalebar instead of my custom solution as it is much more powerful (I wasn't aware of the existence of that package when I started writing microfilm). So your issue prompted me to finally implement this change. If you install the package directly via GitHub using:
```
pip install git+https://github.com/guiwitz/microfilm.git
```
you will have the latest version with those changes added (I didn't do a release on pypi yet). Except for some slight formatting differences, this change should be mostly silent and the main options remain. For details you can look at the description of my PR: https://github.com/guiwitz/microfilm/pull/15#issue-1185420230 

Maybe you can try this new version and let me know how it works for you ?

**Comment by gnies** [comment]
I tried the new version and the scalebar seems to scale very well. Thank you for adding this feature :+1:
